# GitHub Sponsors configuration file
# Place this file at: .github/FUNDING.yml

# GitHub Sponsors username
github: PranavMishra17

# Optional: Add other platforms (uncomment if you use them)
# patreon: your_patreon_username
# ko_fi: your_kofi_username
# buy_me_a_coffee: your_buymeacoffee_username
# custom: ['https://your-custom-sponsor-link.com']
