import type { ToolCall } from './mcp.js';

/**
 * Result of a single mind tool execution.
 */
export interface MindToolResult {
  /** Tool name that was called */
  tool_name: string;
  /** Arguments passed to the tool */
  arguments: Record<string, unknown>;
  /** Formatted content returned by the tool (for LLM consumption) */
  result_content: string;
  /** Execution status */
  status: 'success' | 'error';
  /** Error message if status is 'error' */
  error?: string;
}

/**
 * Overall result of the Mind agent loop for a single conversation turn.
 */
export interface MindResult {
  /** Follow-up text generated by the Mind. Empty string if no follow-up needed. */
  follow_up_text: string;
  /** All tools called during this turn (both recall and conversation tools) */
  tools_called: MindToolResult[];
  /** Raw tool calls as returned by the LLM (for forwarding to client) */
  raw_tool_calls: ToolCall[];
  /** Token usage for the Mind's LLM calls */
  usage?: {
    input_tokens: number;
    output_tokens: number;
  };
  /** Whether the Mind completed before timeout */
  completed: boolean;
  /** Whether exit_convo was called by the Mind */
  exit_convo_used: boolean;
  /** exit_convo reason if used */
  exit_convo_reason?: string;
  /** Duration of the Mind agent loop in milliseconds */
  duration_ms: number;
}

/**
 * Mind activity data sent to clients for UI display.
 */
export interface MindActivity {
  tools_called: Array<{
    name: string;
    args: Record<string, unknown>;
    status: 'success' | 'error';
  }>;
  duration_ms: number;
  completed: boolean;
}
